# Site settings
title: Bán và Căn hộ cho thuê Bình Dương
email: px@tiep.us
description: > # this means to ignore newlines until next key
  Trang tạp chí tổng hợp danh sách và cung cấp dữ liệu các căn hộ bán và cho thuê tại Bình Dương.
meta_description: > # shortened description for meta description tag
  Trang tạp chí tổng hợp danh sách và cung cấp dữ liệu các căn hộ bán và cho thuê tại Bình Dương.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://stack.dailybruin.com" # the base hostname & protocol for your site
image_url: /img/posts # corresponds to directory for post images (cf. https://github.com/opattison/jekyll-figure-image-tag#why-yaml-is-useful-for-storing-images)
twitter_username: _thestack
github_username: dailybruin

# Defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: post
      displayed: Yes

# Outputting
permalink: pretty # don't have `.html` on the end of permalinks
timezone: America/Los_Angeles
paginate: 12 # items per page
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown

# plugins
plugins: [jekyll-paginate]

exclude:
  - .jekyll-cache
